apiVersion: v1
kind: ConfigMap
metadata:
  name: petstore-config
  namespace: petstore
data:
  DB_NAME: "petstore"
  MONGO_URI_STORES: "mongodb://mongodb-stores:27017"
  MONGO_URI_PURCHASES: "mongodb://mongodb-purchases:27017"
  PET_STORE_1_URL: "http://pet-store1:8000"
  PET_STORE_2_URL: "http://pet-store2:8000"
